src/MatBlazor/Components/MatButton/BaseMatButton.cs, src/MatBlazor/Components/MatTextField/MatTextField.cshtml
Under current code the Icons are not available when using FullWidth. 
`<MatTextField bind-Value="@MyString2" Label="Standard FullWidth" Icon="favorite" FullWidth="true"></MatTextField><br/>
<MatTextField bind-Value="@MyString2" Label="Trailing Required FullWidth" Icon="favorite" IconTrailing="true" FullWidth="true" Required="true"></MatTextField><br/>`
=> Show Icons when MatTextField FullWidth="true"

src/MatBlazor/MatBlazor.csproj
Implements workaround for issue https://github.com/aspnet/AspNetCore/issues/9577
This will prevent MatBlazor .razor files from showing up in the project
=> Prevent *.razor files from being packed

src/MatBlazor/MatTable.razor
Fixed a bug with MatTable where LoadData would throw an exception when using the Filter function.
This is present in the master and can be tested on the [demo page](https://www.matblazor.com/Table)
=> MatTable bug where LoadData would throw exception when using Filter

src/MatBlazor.Web/src/matLayoutGrid/matLayoutGrid.scss
I guess they are a typo here. Not all [modes](https://github.com/material-components/material-components-web/blob/master/packages/mdc-layout-grid/_variables.scss) are created, only `desktop`.
Note: Notice I din't recompile js/css (main.js) after the change.
=> Typo. Mode is hardcoded

src/MatBlazor.Web/src/matTextField/matTextField.scss
Fixing https://github.com/SamProf/MatBlazor/issues/129
It's not possible to override mdc padding 0 css from .scss, as a workaround (or solution?) I wrote css rule with a more specific css selector.
=> Improve Full Width Field Text Padding

src/MatBlazor/Components/MatTable/MatTable.razor
The calculation for `TotalPages` now uses `Math.Max(1,...)` to avoid a broken paginator when "*"/-1 is selected.
For the future, I think calculating/setting the TotalPages and other Properties concerning pagination could be refactored because there is a lot of code copies.
@SamProf You can open up a issue if you want to discuss it.
Closes #170
=> MatTable: Fix broken paginator when infinite items selected

src/MatBlazor/Components/MatAutocomplete/BaseMatAutocomplete.cs
Explicitly clear StringValue in ClearText() method - without that, it remains populated if Value is not selected yet.
=> Fix MatAutocomplete StringValue clearing

src/MatBlazor/Components/MatToastContainer/IMatToaster.cs, src/MatBlazor/Services/Toast/MatToaster.cs
This return value will make the interface easier to use.
We want to add several toasts and sometimes use IMatToaster.RemoveToasts to remove the toasts before they disappear. 
Currently i have to iterate over the IMatToaster.Toasts to try to find the matching toasts and then remove it.
=> return Toast instance on IMatToaster.Add method

src/MatBlazor.Web/src/matDialog/matDialog.js, src/MatBlazor/Components/MatDialog/BaseMatDialog.cs
New property that will set the _escapeKeyAction_ and _scrimClickAction_ in MDC Dialog.
If set to false the user is not able to close the dialog by pressing ESC or clicking on the scrim.
You can now use MatDialog as just a modal for ex. a modal loading screen.
=> MatDialog: New CanBeClosed property

src/MatBlazor.Web/src/matNavMenu/matNavMenu.scss, src/MatBlazor/Components/MatNavMenu/MatNavItem.razor
#259 - Adds additional functionality to the Nav Menu. Sets MatNavMenu items to be active automatically. Still has one issue where if the MatNavMenu item is a SubMenuNavItem the parent is not activated. This for 2 reasons: NavLink does not have a property that we can read if it is active. CSS does not have a Parent selector. Maybe there is some Material Javascript that I don't know of but at least this is a good start.
=> #259 - Auto-Active MatNatItem

README.md
As described in #152, it is not clear that you need to install "EmbeddedBlazorContent".
Additionaly the doc is missing a using statment.
As also discussed in #152, this way might not be necessary anymore. But currently it is.
=> Update Readme.md according to #152

src/MatBlazor/Components/MatList/BaseMatList.cs
Initialising `_selectedIndex `to `-1` allows setting the default selected item to the first item in the list. 
Currently `_selectedIndex `is initialised by default to `0`, therefore calling `SetSelectedIndex(0)` does not yield the correct result, because of: `if (_selectedIndex != index)`
=> Matlist selectedIndex default value set to -1

src/MatBlazor/Components/MatTable/TableRow.razor
To prevent rendering errors when diffing the dom tree.
=> Added @key attribute to MatTable table row

src/MatBlazor/Core/MatBlazorSwitchTByte.cs, src/MatBlazor/Core/MatBlazorSwitchTChar.cs, src/MatBlazor/Core/MatBlazorSwitchTInt.cs, src/MatBlazor/Core/MatBlazorSwitchTLong.cs, src/MatBlazor/Core/MatBlazorSwitchTSByte.cs, src/MatBlazor/Core/MatBlazorSwitchTShort.cs, src/MatBlazor/Core/MatBlazorSwitchTUInt.cs, src/MatBlazor/Core/MatBlazorSwitchTULong.cs, src/MatBlazor/Core/MatBlazorSwitchTUShort.cs
I corrected a small issue making the NumericDropDown making overflow.
=> Prevent circular overflow on MatNumericUpDownField - issue #373

src/MatBlazor.Demo/Demo/DemoMatNavMenu.razor, src/MatBlazor.Demo/Shared/DemoDrawerContent.razor, src/MatBlazor/Components/MatNavMenu/BaseMatNavItem.cs, src/MatBlazor/Components/MatNavMenu/MatNavItem.razor, src/MatBlazor/MatBlazor.xml
- Fix for #393, Fixes MatNavItem so that if Disabled=true it will not redirect. 
- Fix for #319 Additionally this adds an OnClick Functionality to the MatNavItem so you can do a custom method if a redirect is not what you want to do.
=> Fix #393, Fix #319, MatNavItem still clickable when disabled=true. Add OnClick to MatNavItem

src/MatBlazor.Demo/Doc/DocMatAccordion.razor, src/MatBlazor.Demo/Doc/DocMatExpansionPanel.razor, src/MatBlazor/Components/MatAccordion/BaseMatAccordion.cs, src/MatBlazor/Components/MatAccordion/BaseMatExpansionPanel.cs, src/MatBlazor/Components/MatAccordion/MatExpansionPanelSummary.razor, src/MatBlazor/MatBlazor.xml
Hello!
First of all, thank you for your great work with this repository. I'm looking forward to use MatBlazor in upcoming Blazor projects!
I've added the ability to be able to hide the toggle button in MatAccordion and MatExpansionpanel similar to how Angular has done in their implementation of Material. With this change you can get a cleaner accordion in some cases when you don't want the arrow in the summary. See Angular stackblitz example below (From their docs)
https://stackblitz.com/angular/qkjarbvydory?file=src%2Fapp%2Fexpansion-steps-example.ts
I added some XML comments for the parameters and ran the DevUtils before committing, I hope everything is in order - if not please reply.
Best regards
Victor Lindespång
=> Added ability to hide toggle button in MatAccordion / MatExpansionpanel

src/MatBlazor.Demo/Shared/DemoDrawerContent.razor, src/MatBlazor/Components/MatNavMenu/BaseMatNavItem.cs, src/MatBlazor/Components/MatNavMenu/MatNavItem.razor, src/MatBlazor/MatBlazor.xml
Fixes Home / root always active even when not on the / path.
=> #455 - Add Parameter to MatNavItem to allow user to set the NavLinkMatch

src/MatBlazor.Web/package.json, src/MatBlazor.Web/webpack/prod.config.js
- Source1 (remove node-sass): https://github.com/material-components/material-components-web/issues/5502#issuecomment-586061492
- Source2 (temporary workaround): https://github.com/webpack-contrib/sass-loader/issues/804#issuecomment-586095020
https://github.com/SamProf/MatBlazor/issues/479
=> [#479] Remove node-sass and add temporary workaround for sass-loader.

src/MatBlazor.Web/src/matTextField/matTextField.scss
Add `!important` to a padding so it works on leading icon.
=> Correct padding for MatTextField with leading icon #276

src/MatBlazor.Web/src/matAccordion/matAccordion.scss
- This fixes problems with contents that have over 1000px height
- Same solution is used in material-ui's Collapse https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/Collapse/Collapse.js
https://github.com/SamProf/MatBlazor/issues/477
=> [#477] Use height instead of max-height in mat-expansion-panel base/expanded

src/MatBlazor.Web/src/matTextField/matTextField.scss
Added style to change label color to use theme's primary color.
Material design have this default value for the label
.mdc-text-field--focused:not(.mdc-text-field--disabled) .mdc-floating-label {
color: rgba(98,0,238,0.87);
}
So I just changed to use the theme primary color
.mdc-text-field--focused:not(.mdc-text-field--disabled) .mdc-floating-label {
color: var(--mdc-theme-primary, #6200ee);
}
The result is
The only problem is that I **haven't test it when building the application**, only edit in the browser to test it.
So before merging, **please build the app and test this**.
My concern is that the css won't override the `mdc` classes.
=> Added label color to theme primary color

src/MatBlazor.Web/src/matSelect/matSelect.scss
Before 
After
The icon of the select still need to change the color (or not), but this should be revised in the material design guide lines.
I just didn't do it because the "icon" is an image from a svg and I have no ideia how to change the color of that
=> Added Primary Color to MatSelect Label

src/MatBlazor/Components/MatAutocompleteList/BaseMatAutocompleteList.cs
I fixed it to update the Value when closing the dialog(to not keep old references which are no longer represented by the StringValue + When changing the value, even if the value will be the same it is possible to need to update the StringValue:
e.g. Select One, delete e, Select One.
=> Fixed #545 Can't select item in MatAutocompleteList 

src/MatBlazor/Components/MatAutocompleteList/BaseMatAutocompleteList.cs, src/MatBlazor/Components/MatAutocompleteList/MatAutocompleteList.razor, src/MatBlazor/MatBlazor.xml
This allows to use keyboard based trigger to clear current text in
autocomplete. This also requires using base event type in method
definition.
Thanks!
=> Allow keyboard triggered clear text event on MatAutocomplete

src/MatBlazor.Demo/Demo/DemoAutocomplete.razor, src/MatBlazor.Demo/Demo/DemoAutocompleteList.razor, src/MatBlazor/Components/MatAutocompleteList/AutocompleteListSearchResult.cs, src/MatBlazor/Components/MatAutocompleteList/BaseMatAutocompleteList.cs, src/MatBlazor/Components/MatAutocompleteList/MatAutocompleteList.razor
Issues Fixed:
https://github.com/SamProf/MatBlazor/issues/315
https://github.com/SamProf/MatBlazor/issues/430
https://github.com/SamProf/MatBlazor/issues/246 - partial
https://github.com/SamProf/MatBlazor/issues/213
Also as all of them were related to the edit form I added an example in the demo using the EditForm + MatAutocompleteList and validation for the selected option.
This feature is also resolved already so can be closed: https://github.com/SamProf/MatBlazor/issues/267
=> Fixed multiple Autocomplete Issues

src/MatBlazor.Demo/Demo/DemoMatSelectItem.razor, src/MatBlazor.Demo/Demo/DemoMatSelectValue.razor
* fixes typos "vlaue" -> "value" in the follwing demos
* DemoMatSelectItem
* DemoMatSelectValue
=> Fix typo in MatSelect demos

src/MatBlazor/Components/MatAccordion/BaseMatAccordion.cs, src/MatBlazor/Components/MatAccordion/BaseMatExpansionPanel.cs, src/MatBlazor/Components/MatAccordion/MatExpansionPanelDetails.razor
Hi!
Yeah so I was migrating my Blazor server app to webassembly now since the general release a few days ago and I noticed the rendering is quite a lot slower compared to Blazor server (have not played with webassembly before actually) - hopefully this get a big improvement from AOT compilation which is next milestone for blazor webassembly. As of now I have to look into where I can make performance improvements in both my own code and in MatBlazor
_(...which lead up to this pull request)_
First step is that I added the ability of _opt-in_ lazy rendering for the details view in the accordion / expansionpanel - this means that the HTML of the details view is not rendered until you expand the panel. The current behaviour (_which will also continue to be the default behavior_) is that the …
=> Added lazy rendering for matexpansionpanel details + bug fix

src/MatBlazor/Components/MatFileUpload/BaseMatFileUpload.cs, src/MatBlazor/Components/MatFileUpload/MatFileUpload.razor
The documentation for MatFileInput gives an example of being able to select or drop multiple files into the component for processing. The component currently only allows single file selection. This change enables the multiple file selection/drop into the component.
=> Enables multiple file upload on MatFileInput component

src/MatBlazor.Demo/Demo/DemoMatSelect.razor, src/MatBlazor/Core/MatBlazorSwitchT.cs, src/MatBlazor/Core/MatBlazorSwitchTGuid.cs, src/MatBlazor/Core/MatBlazorSwitchTGuidNull.cs
To support GUID and GUID? within MatSelect this PR is adding two implementations:
* Implemented MatBlazorSwitchTGuid
* Implemented MatBlazorSwitchTGuidNull
=> MatSelect - Adding support for GUID / GUID?

src/MatBlazor.Demo/Demo/DemoMatSelect.razor, src/MatBlazor.Web/README.md, src/MatBlazor.Web/deploy.df, src/MatBlazor.Web/deploy.df.dockerignore, src/MatBlazor.Web/deploy.ps1, src/MatBlazor/Core/MatBlazorSwitchT.cs, src/MatBlazor/Core/MatBlazorSwitchTGuid.cs, src/MatBlazor/Core/MatBlazorSwitchTGuidNull.cs
This change adds a powershell script and a Dockerfile to help deploy js/css static assets on a machine without npm.
How it works:
- when the docker container is built, it creates the up-to-date resources. Changes to any file will trigger a rebuild.
- the resources are then essentially just copied out of the image, overwriting the files in the dist folder.
The main advantage of this approach is that the deploy step doesn't require setting up npm anymore (and one doesn't have to worry about environments, as it's a fresh environment). Of course that's traded against the requirement of docker + powershell (a similar bash script would be very easy to add, if some developers are unix-based).
=> Simplify deploying js/css

src/MatBlazor/Components/MatTextField/BaseMatInputTextComponent.cs
This addresses #659.
There are still issues here, but I think it's probably in JS: when focus is lost on the textfield, the `mat-floating-label--float-above` is removed, irrespective of existance of text or placeholder. Needs some more investigation.
What's fixed here is the situation where overlap occurs when the value is not just whitespace or when the placeholder is not just whitespace and should be visible.
=> Fix part of #659

src/MatBlazor/Components/MatTable/MatTable.razor
I was receiving exceptions for abstract base types, the change in this pull request fixes the problem.
=> Fix instantiation attempts for abstract types for multi column filtering in MatTable

src/MatBlazor.Demo.ClientApp/MatBlazor.Demo.ClientApp.csproj, src/MatBlazor/Components/MatButton/BaseMatButton.cs, src/MatBlazor/MatBlazor.xml
This is an issue with JSInterop, where it natively awaits the JS task, but does not throw an exception to show that the task timed out. 
https://github.com/dotnet/aspnetcore/issues/18875
https://github.com/dotnet/aspnetcore/issues/21384
The second issue in the description indicates that MS will need to do something to allow a more specific exception that can be caught in the try/catch, though the TaskCanceledException is enough for now.
=> Bugfix/#713 - Task canceled exception

src/MatBlazor.Demo/Demo/DemoMatSlider.razor, src/MatBlazor.Web/src/matSlider/matSlider.js, src/MatBlazor/Components/Base/BaseMatInputComponent.cs, src/MatBlazor/Components/MatSlider/BaseMatSlider.cs
Fixes #661 and #332 
Whenever bound value updates, slider reflects changes. It works with Value, ValueMin, ValueMax, Step for now
=> Enable slider values update from code

src/MatBlazor/Components/MatTable/MatTable.razor
Fixed a null reference exception.
=> Fix null reference exception for multi column filtering in MatTable

src/MatBlazor/Components/MatDatePicker/BaseMatDatePickerInternal.cs, src/MatBlazor/Components/MatDatePicker/FlatpickrOptions.cs
I think these are the required changes to allow a localized Flatpickr component, #714 
Unfortunately i was unable to use the compiled MatBlazor.dll in a test project.
=> MatDatePicker Localized feature

src/MatBlazor.Demo/Demo/DemoMatButtonLink.razor, src/MatBlazor.Demo/Pages/DemoMatButtonLinkPage.razor, src/MatBlazor.Demo/Shared/DemoDrawerContent.razor, src/MatBlazor.Web/src/matButton/matButton.scss, src/MatBlazor/Components/MatLink/BaseMatLink.cs, src/MatBlazor/Components/MatLink/MatLink.razor
**`MatButtonLink`** is a link component styled exactly like a `MatButton`.
The `MatButton` component already has a `Link` parameter but it is in fact a _button_ and doesn't have the features of a _link_ like being able to open in a new tab, copying the link address e.t.c....
The styles are based on `mdc-button` styles, but extra styles are added for a class "mat-button-link"
It doesn't have `Name`, `Value`, `Label` and `Type` params which are present in `MatButton`, and `Link` param was renamed to `Href`. Every other parameter from `MatButton` is present.
=> Added component MatButtonLink

src/MatBlazor/Components/MatChip/MatChip.razor
It looks like the update to MDC 7.0.0 ended up braking the MatChip component's TrailingIconClick. According to [this MDC issue](https://github.com/material-components/material-components-web/issues/6136) it's because the `mdc-chip-trailing-action` CSS class should be on the remove trailing icon. This PR adds this class.
I've confirmed locally that the TrailingIconClick event fires when this change is made. This should resolve [issue #724](https://github.com/SamProf/MatBlazor/issues/724).
=> Fixes MatChip TrailingIconClick

src/MatBlazor/Components/MatSlideToggle/MatSlideToggle.razor
The MatSlideToggle component contains a duplicate id which is breaking accessibility.
Related to [845](https://github.com/SamProf/MatBlazor/issues/845)
=> Remove duplicate Id

src/MatBlazor.Demo/Demo/DemoMatRadioButton.razor, src/MatBlazor.Demo/Doc/DocMatRadioGroup.razor, src/MatBlazor/Components/MatButtonLink/BaseMatLink.cs, src/MatBlazor/Components/MatNavMenu/BaseMatNavItem.cs, src/MatBlazor/Components/MatRadioButton/BaseMatRadioGroupInternal.cs, src/MatBlazor/Components/MatRadioButton/MatRadioButtonInternal.razor
This pull request introduces a feature and a fix, but I didn't know how to seperate them into different pull requests.
1. Added the ability to specify a custom group name to be used to group radio buttons. If not specified, the Group.Id will be used instead. This pull request addresses most of #789.
2. Fixed double navigation for MatNavItem and MatButtonLink. This pull request addresses #802. The cause of the double Navigation was UriHelper.NavigateTo(). Since it is already a link, this isn't needed unless ForceLoad is true.
=> Specify a group name for MatRadioButtons on the MatRadioGroup and Double Navigation Fix

src/MatBlazor.Demo/Demo/DemoThemes.razor, src/MatBlazor.Web/src/matTextField/matTextField.scss
I was using matblazor and my custom theme with dark color. I set background and surface as black but MatTextField still had white bg-color.
So, setting bg-color from -mdc-theme-surface is expected behavior for me. Only some elements (like table) use color from -mdc-theme-surface.
And this problem also connect with #82 
1. Add surface color picker to DemoThemes
2. Add `background-color: var(--mdc-theme-surface, #fff)`  to MatTextField
I had some problems with this fix: it wasn't work after adding bg-color to `.mdc-text-field` because `mdc-text-field--filled:not(.mdc-text-field--disabled)` override this value. I don't know matblazor good enough and have no idea how to change generated value for `.mdc-text-field--filled:not(.mdc-text-field--disabled)` (there is no declaration for this class …
=> feat: apply surface color as background color for text field component

src/MatBlazor/Components/MatTable/BaseMatTable.cs, src/MatBlazor/MatBlazor.xml
Both use Action instead of EventCallback, because the search filter is creating its own asynchronous operation which causes a dispatcher error.
=> Enabling PageSize and CurrentPage to be bound to on MatTable

src/MatBlazor/Components/MatNavMenu/BaseMatNavItem.cs
Related to #442
Could be that this intended behavior.
OnClick would not be triggered once Href was set.
=> NavItem OnClick was ignored.
