SamProf/MatBlazor

- src/MatBlazor.Demo/Demo/DemoMatCheckbox.cshtml
- src/MatBlazor/Components/MatCheckbox/BaseMatCheckbox.cs
- src/MatBlazor/Components/MatCheckbox/MatCheckbox.cshtml
#41 Allow for inline Label / ChildContent for MatCheckbox
> MatCheckbox add inline label & update demo

- src/MatBlazor.Demo/Demo/DemoAutocomplete.cshtml
- src/MatBlazor.Web/src/matAutocomplete/matAutocomplete.scss
- src/MatBlazor/Components/MatAutocomplete/BaseMatAutocomplete.cs
- src/MatBlazor/Components/MatAutocomplete/MatAutocomplete.cshtml
Hi again!
I also added more demos for Autocomplete(With Icon, With Clear button and FullWidth)
+ Fixed another issue regarding Autocomplete regarding PreSelected Item: e.g Demo with a clear button where the selected item is 'one' by default.
Thanks!
Have a nice day
> Fixed #50 Autocomplete FullWidth + 

- src/MatBlazor/Components/MatAutocomplete/BaseMatAutocomplete.cs
- src/MatBlazor/MatBlazor.csproj
Hi!
I added some documentation for MatAutocomplete and fixed #56.
Thanks!
Have a nice day!
> Added documentation for autocomplete + Fixed #56 + changed documentation file path to a relative one(instead of absolut)

- src/MatBlazor/Components/MatTable/MatTable.cshtml
First and Last were not working in my version 1. The code I used had the error and I did not check. Tested now and working.
> Fix Table Navigation Error

- src/MatBlazor/Components/MatTable/BaseMatTable.cs
- src/MatBlazor/Components/MatTable/MatTable.razor
- src/MatBlazor/MatBlazor.csproj
Reverted c# 8.0 Switch Expression back to 7.3.
> Revert to C# 7.3

- src/MatBlazor/Components/MatNumericUpDownField/BaseMatNumericUpDownField.cs
- src/MatBlazor/MatNumericUpDownField.razor
Hi,
this component is base on MatTextField and it has a behavior like [NumericUpDownField](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/numericupdown-control-overview-windows-forms).
You can view the control in action with this code:
```
@page "/NumericUpDownField"
<h4>Counter 1: [@(testingNullableDecimal1?.ToString() ?? "No value")] </h4>
<h4>Counter 2: [@(testingNullableDecimal2?.ToString() ?? "No value")] </h4>
<MatButton OnClick="@Click">ClickMe @ButtonState</MatButton>
<br/>
<MatNumericUpDownField 
bind-Value=@testingNullableDecimal1 
DecimalPlaces=2>
</MatNumericUpDownField>
<MatNumericUpDownField 
bind-Value=@testingNullableDecimal2 
DecimalPlaces=0 
Minimum=null Maximum=null >
</MatNumericUpDownField>
@functions
{
decimal? testingNullableDecimal1 = 0; …
```
> MatNumericUpDownField

- src/MatBlazor/Components/MatNumericUpDownField/BaseMatNumericUpDownField.cs
- src/MatBlazor/MatNumericUpDownField.razor
>... [please make 2 changes](https://github.com/SamProf/MatBlazor/pull/95#issuecomment-500403637) ...
Hi. Here they are. Thanks.
> up down alltime visible no selectable

- src/MatBlazor/MatTable.razor
Added OnParametersSetAsync so LoadData would be called if data changed after page load.
There is some Table issues open at the moment that will be resolved with this fix.
> Fixed a bug where Table would not re render after data changed.

- src/MatBlazor.Demo/Demo/DemoMatList.razor
- src/MatBlazor.Demo/Demo/DemoToast.razor
- src/MatBlazor/Components/MatList/BaseMatListItem.cs
- src/MatBlazor/Components/MatList/MatListItem.razor
- src/MatBlazor/MatBlazor.xml
Added Disabled Attribute to MatListItem. Updated MatToaster config for documentation
> MatListItem Disabled

- src/MatBlazor.Demo/Demo/DemoTable.razor
- src/MatBlazor.Web/src/matTable/matTable.scss
- src/MatBlazor/Components/MatList/BaseMatListItem.cs
#88 MatTable style updates, demo
> #88 MatTable style updates

- src/MatBlazor.Demo/Demo/DemoMatTextField.razor
- src/MatBlazor/Components/MatDatePicker/BaseMatDatePicker.cs
- src/MatBlazor/Components/MatTextField/BaseMatTextField.cs
- src/MatBlazor/Components/MatTextField/MatTextField.razor
Changed the helper text in MatTextField according to https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield#text-field-with-helper-text
> Fixed up the helper text functionality in MatTextField.

- src/MatBlazor.Demo/Demo/DemoMatSelect.razor
- src/MatBlazor.Web/src/matSelect/matSelect.js
- src/MatBlazor/Components/MatSelect/BaseMatSelect.cs
- src/MatBlazor/Components/MatSelect/MatSelect.razor
Brought MatSelect up to par with MatTextField and added some JavaScript functions that can be used when necessary.
> MatSelect Updates

- src/MatBlazor.Web/src/main.js
- src/MatBlazor.Web/src/matNumericUpDownField/matNumericUpDownField.js
Fix upper cases to compile npm on Linux and mac systems.
> fix upper cases for linux env

- src/MatBlazor/Components/MatNumericUpDownField/BaseMatNumericUpDownField.cs
- src/MatBlazor/Components/MatNumericUpDownField/MatNumericUpDownField.razor
Fixing NumericUpDown issues:
* Tabindex ( skip up and down arrows pressing tabs, go to next field )
* Issue setting value from UI fixed.
> NumericUpDown to preview7. Fix tabindex

- src/MatBlazor.Web/src/matNavMenu/matNavMenu.scss
- src/MatBlazor/Components/MatNavMenu/MatNavSubMenuHeader.razor
As requested by @SamProf Fix Double Hover / Click on Nav Sub Header
> #167 Fix Double Hover / Click on Nav Sub Header

- src/MatBlazor.Demo/Demo/DemoMatNavMenu.razor
- src/MatBlazor/Components/MatNavMenu/BaseMatNavMenu.cs
- src/MatBlazor/Components/MatNavMenu/BaseMatNavSubMenu.cs
- src/MatBlazor/Components/MatNavMenu/IMatNavSubMenuToggler.cs
As [requested](https://github.com/SamProf/MatBlazor/pull/174#issuecomment-519378958), an example showing nested sub menus 3 levels deep.
> Adding example for nested sub menus and new "toggle all" feature

- src/MatBlazor/Components/MatTable/BaseMatTable.cs
- src/MatBlazor/Components/MatTable/MatTable.razor
- src/MatBlazor/MatBlazor.xml
This is the fix for Issue #288
> #288 Fixed "Items per Page"

- README.md
Update BlazorBoilerplate description to make it more obvious what it is and link to the demo
> Update BlazorBoilerplate description

- src/MatBlazor/Components/MatTable/MatTable.razor
Allow filtering on multiple columns, instead of just one
> Filtering on multiple columns

- src/MatBlazor/Components/MatTabGroup/MatTabGroup.razor
This fixes some form validation issues I was having across multiple tabs
> added @key attribute to MatTab content

- README.md
The prerequisites are not up to date as far as I can tell. I adjusted them to the best of my knowledge.
> Updated prerequisites

- src/MatBlazor.Web/src/matTooltip/matTooltip.js
Typo Fix that fixes Tooltip Right position
> ToolTip Typo Fix

- src/MatBlazor/Components/MatSelect/CoreMatSelect.razor
> #453 - Add Id and Attribute to MatSelect

- src/MatBlazor.Demo/Demo/DemoTable.razor
- src/MatBlazor/Components/MatTable/BaseMatTable.cs
- src/MatBlazor/Components/MatTable/BaseTableRow.cs
- src/MatBlazor/Components/MatTable/MatTable.razor
Added an event to the MatTable, which returns the item of the selected row to the ParentComponent where the Table has been built.
> Added, return item object from selected row event.

- src/MatBlazor.Demo/Demo/DemoMatSlideToggle.razor
Fixes https://github.com/SamProf/MatBlazor/issues/177.
> Added documentation for SlideToggle value changed event.

- src/MatBlazor/Components/MatTable/MatTable.razor
Check issue #559 for a perfect explanation of the problem.
Solution: Initialize StartPage on Component initialize
> Bugfix for pagecounter in MatTable, fixes #559

- src/MatBlazor.Demo/Demo/DemoMatNavMenu.razor
- src/MatBlazor.Demo/Doc/DocMatNavMenu.razor
- src/MatBlazor/Components/MatNavMenu/BaseMatNavItem.cs
- src/MatBlazor/Components/MatNavMenu/MatNavItem.razor
- src/MatBlazor/Components/MatNavMenu/MatNavSubMenuHeader.razor
- src/MatBlazor/MatBlazor.xml
Fixes https://github.com/SamProf/MatBlazor/issues/602.
> Added mouse over texts for MatNavMenu components, adjusted examples.

- src/MatBlazor.Demo/Demo/DemoMatSlider.razor
- src/MatBlazor/Components/MatSlider/BaseMatSlider.cs
- src/MatBlazor/Components/MatSlider/MatSlider.razor
Update Slider to add Pins & Markers closer to the Material Design options:
https://material-components.github.io/material-components-web-components/demos/slider/
> Update Slider to Add Pin & Markers

- src/MatBlazor.Demo/Shared/MainLayout.razor
Appbar on demo page is responsive.
Icons at end change to menu
> Responsive menu on Demo page, icons change to menu on smaller screens.

- src/MatBlazor.DevUtils/DemoContentGenerator.cs
Spaces in folder break DemoContentGenerator.Generate()
> Spaces in folder name's break DemoContentGenerator.Generate()

- src/MatBlazor.Demo/Demo/DemoEditContext.razor
- src/MatBlazor.Demo/Demo/DemoMatRadioButton.razor
> Language improvements

- src/MatBlazor.Web/src/matTextField/matTextField.scss
Fix for  #619 . from @kristof12345 / #642
> PR #642. Fixes #619 Validation styles for outlined Text fields

- src/MatBlazor.Web/src/matTextField/matTextField.scss
#694 
TextField Label should be transparent as Default
> TextField Label should be transparent as Default

- src/MatBlazor.Demo.ClientApp/MatBlazor.Demo.ClientApp.csproj
- src/MatBlazor.Demo/MatBlazor.Demo.csproj
- src/MatBlazor.DevUtils/MatBlazor.DevUtils.csproj
- src/MatBlazor.TestApp.ServerApp/MatBlazor.TestApp.ServerApp.csproj
- src/MatBlazor/MatBlazor.csproj
Some of the packages have become stale, so updating
> Update MatBlazor Packages

- src/MatBlazor/Components/MatAccordion/MatAccordion.razor
- src/MatBlazor/Components/MatAccordion/MatAccordion.razor.cs
- src/MatBlazor/Components/MatAccordion/MatExpansionPanel.razor
- src/MatBlazor/Components/MatAccordion/MatExpansionPanel.razor.cs
- src/MatBlazor/Components/MatAccordion/MatExpansionPanelDetails.razor
- src/MatBlazor/Components/MatAccordion/MatExpansionPanelDetails.razor.cs
- src/MatBlazor/Components/MatAccordion/MatExpansionPanelHeader.razor
- src/MatBlazor/Components/MatAccordion/MatExpansionPanelHeader.razor.cs
- src/MatBlazor/Components/MatAccordion/MatExpansionPanelSubHeader.razor
- src/MatBlazor/Components/MatAccordion/MatExpansionPanelSubHeader.razor.cs
- src/MatBlazor/Components/MatAccordion/MatExpansionPanelSummary.razor
- src/MatBlazor/Components/MatAccordion/MatExpansionPanelSummary.razor.cs
- src/MatBlazor/Components/MatAnchor/MatAnchorContainer.razor
- src/MatBlazor/Components/MatAnchor/MatAnchorContainer.razor.cs
- src/MatBlazor/Components/MatAnchor/MatAnchorLink.razor
- src/MatBlazor/Components/MatAnchor/MatAnchorLink.razor.cs
- src/MatBlazor/Components/MatAnchor/MatAnchorUtils.cs
@enkodellc only cosmetic changes for now, before starting with contributions I like to make code cleaner and understand how it runs.
> Accordion Cleanup code and removed redundant base class

- src/MatBlazor/Components/MatTable/MatTable.razor
The current solution does not work and is not logical. I offer my fixes for getting the page object from the api.
> Fix load paging data to MatTable.

- src/MatBlazor/Components/MatAutocompleteList/AutocompleteListSearchResult.cs
- src/MatBlazor/Components/MatAutocompleteList/BaseMatAutocompleteList.cs
https://github.com/SamProf/MatBlazor/issues/790
> Fix MatAutocompleteList re-render list on items update

- src/MatBlazor.Demo/Doc/DocMatFileUpload.razor
- src/MatBlazor/Components/MatFileUpload/BaseMatFileUpload.cs
- src/MatBlazor/Components/MatFileUpload/MatFileUpload.razor
MatFileUpload was missing an option to set html accept attribute. Pull request includes docs update.
> Add accept attribute to MatFileUpload component.
